---
version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=sace
      - POSTGRES_USER=sace
    ports:
      - 5433:5432
    volumes:
      - sace-db-data:/var/lib/postgresql/data

volumes:
  sace-db-data: