--liquibase formatted sql
--changeset samuelcluna:create-reservation-table context:new splitStatements:true endDelimiter:;

CREATE TABLE reservation
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created-at"    TIMESTAMP WITHOUT TIME ZONE,
    "updated-at"    TIMESTAMP WITHOUT TIME ZONE,
    start_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    court_id        BIGINT                                  NOT NULL,
    sace_user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_reservation PRIMARY KEY (id)
);

ALTER TABLE reservation
    ADD CONSTRAINT fk_reservation_on_court FOREIGN KEY (court_id) REFERENCES court (id);

ALTER TABLE reservation
    ADD CONSTRAINT fk_reservation_on_user FOREIGN KEY (sace_user_id) REFERENCES sace_user (id);
