--liquibase formatted sql
--changeset samuelcluna:create-unavailable-reservation-table context:new splitStatements:true endDelimiter:;

CREATE TABLE unavailable_reservation
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created-at"    TIMESTAMP WITHOUT TIME ZONE,
    "updated-at"    TIMESTAMP WITHOUT TIME ZONE,
    start_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    court_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_unavailable_reservation PRIMARY KEY (id)
);

ALTER TABLE unavailable_reservation
    ADD CONSTRAINT fk_unavailable_reservation_on_court FOREIGN KEY (court_id) REFERENCES court (id) ON DELETE CASCADE;