--liquibase formatted sql
--changeset samuelcluna:create-sign-up-confirmation-code-table context:new splitStatements:true endDelimiter:;

CREATE TABLE sign_up_confirmation_code
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created-at"      TIMESTAMP WITHOUT TIME ZONE,
    "updated-at"      TIMESTAMP WITHOUT TIME ZONE,
    sace_user_id      BIGINT                                  NOT NULL,
    confirmation_code VARCHAR(255)                            NOT NULL,
    expirates_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_sign_up_confirmation_code PRIMARY KEY (id)
);

ALTER TABLE sign_up_confirmation_code
    ADD CONSTRAINT uc_sign_up_confirmation_code_sace_user UNIQUE (sace_user_id);

ALTER TABLE sign_up_confirmation_code
    ADD CONSTRAINT fk_sign_up_confirmation_code_on_sace_user FOREIGN KEY (sace_user_id) REFERENCES sace_user (id);
