--liquibase formatted sql
--changeset samuelcluna:create-user-table context:new splitStatements:true endDelimiter:;

CREATE TABLE sace_user
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created-at" TIMESTAMP WITHOUT TIME ZONE,
    "updated-at" TIMESTAMP WITHOUT TIME ZONE,
    name         VARCHAR(255)                            NOT NULL,
    username     VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(255)                            NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    student_id   VARCHAR(255),
    CONSTRAINT pk_sace_user PRIMARY KEY (id)
);

ALTER TABLE sace_user
    ADD CONSTRAINT uc_sace_user_student UNIQUE (student_id);

ALTER TABLE sace_user
    ADD CONSTRAINT uc_sace_user_username UNIQUE (username);